# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b5b383470db6bc404712aa45ce11e0f12fb81cec80bb5177e20902eacb41a2374d3e9b3ffa6cb202627bc9f5a43d3dc5f0a25d6c67d364df2482b97b180156d

test:
  secret_key_base: 0a5b2a0e705a282b40e79b0c06b105605aa2ead245ec684ffd4122f5ac914d7af292531cd70fdee07014299febc916c3a9854a48b42fb6115fdfbfc2e7634f00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0a5b2a0e705a282b40e79b0c06b105605aa2ead245ec684ffd4122f5ac914d7af292531cd70fdee07014299febc916c3a9854a48b42fb6115fdfbfc2e7634f00
